# PATHS
RAW_AUDIO_PATH = 'data/raw/audio/'
PROCESS_AUDIO_PATH = 'data/processed/audio/'

# GLOBAL SETTINGS
DB_SIZE = 100

# DATA PROCESSING
SAMPLE_RATE = 44100
FRAME_SIZE = 0.025
FRAME_STRIDE = 0.01
FRAME_LENGTH = 64
HOP_SIZE = 32
WINLEN = 0
WINSHIFT = 0